import process from "node:process"
import { Interval } from "./consts"
import { typeSafeObjectFromEntries } from "./type.util"
import type { OriginSource, Source, SourceID } from "./types"

const Time = {
  Test: 1,
  Realtime: 2 * 60 * 1000,
  Fast: 5 * 60 * 1000,
  Default: Interval, // 10min
  Common: 30 * 60 * 1000,
  Slow: 60 * 60 * 1000,
}

export const originSources = {
  "v2ex": {
    name: "V2EX",
    color: "slate",
    home: "https://v2ex.com/",
    sub: {
      share: {
        title: "最新分享",
        column: "tech",
      },
    },
  },
  "zhihu": {
    name: "知乎",
    type: "hottest",
    column: "china",
    color: "blue",
    home: "https://www.zhihu.com",
  },
  "weibo": {
    name: "微博",
    title: "实时热搜",
    type: "hottest",
    column: "china",
    color: "red",
    interval: Time.Realtime,
    home: "https://weibo.com",
  },
  "zaobao": {
    name: "联合早报",
    interval: Time.Common,
    type: "realtime",
    column: "world",
    color: "red",
    desc: "来自第三方网站: 早晨报",
    home: "https://www.zaobao.com",
  },
  "coolapk": {
    name: "酷安",
    type: "hottest",
    column: "tech",
    color: "green",
    title: "今日最热",
    home: "https://coolapk.com",
  },
  "mktnews": {
    name: "MKTNews",
    column: "finance",
    home: "https://mktnews.net",
    color: "indigo",
    interval: Time.Realtime,
    sub: {
      flash: {
        title: "快讯",
      },
    },
  },
  "wallstreetcn": {
    name: "华尔街见闻",
    color: "blue",
    column: "finance",
    home: "https://wallstreetcn.com/",
    sub: {
      quick: {
        type: "realtime",
        interval: Time.Fast,
        title: "快讯",
      },
      news: {
        title: "最新",
        interval: Time.Common,
      },
      hot: {
        title: "最热",
        type: "hottest",
        interval: Time.Common,
      },
    },
  },
  "36kr": {
    name: "36氪",
    type: "realtime",
    color: "blue",
    home: "https://36kr.com",
    column: "tech",
    sub: {
      quick: {
        title: "快讯",
      },
      renqi: {
        type: "hottest",
        title: "人气榜",
      },
    },
  },
  "douyin": {
    name: "抖音",
    type: "hottest",
    column: "china",
    color: "gray",
    home: "https://www.douyin.com",
  },
  "hupu": {
    name: "虎扑",
    home: "https://hupu.com",
    column: "china",
    title: "主干道热帖",
    type: "hottest",
    color: "red",
  },
  "aihot": {
    name: "AIHOT",
    type: "realtime",
    column: "tech",
    color: "blue",
    interval: Time.Fast,
    home: "https://aihot.virxact.com/all",
  },
  "tieba": {
    name: "百度贴吧",
    title: "热议",
    column: "china",
    type: "hottest",
    color: "blue",
    home: "https://tieba.baidu.com",
  },
  "toutiao": {
    name: "今日头条",
    type: "hottest",
    column: "china",
    color: "red",
    home: "https://www.toutiao.com",
  },
  "ithome": {
    name: "IT之家",
    color: "red",
    column: "tech",
    type: "realtime",
    home: "https://www.ithome.com",
  },
  "thepaper": {
    name: "澎湃新闻",
    interval: Time.Common,
    type: "hottest",
    column: "china",
    title: "热榜",
    color: "gray",
    home: "https://www.thepaper.cn",
  },
  "sputniknewscn": {
    name: "卫星通讯社",
    color: "orange",
    column: "world",
    home: "https://sputniknews.cn",
  },
  "cankaoxiaoxi": {
    name: "参考消息",
    color: "red",
    column: "world",
    interval: Time.Common,
    home: "https://china.cankaoxiaoxi.com",
  },
  "pcbeta": {
    name: "远景论坛",
    color: "blue",
    column: "tech",
    // 站点只允许 TLS1.2 并在通过环境校验后强制滑块验证码，服务端无法抓取
    disable: true,
    home: "https://bbs.pcbeta.com",
    sub: {
      windows11: {
        title: "Win11",
        type: "realtime",
        interval: Time.Fast,
      },
      windows: {
        title: "Windows 资源",
        type: "realtime",
        interval: Time.Fast,
        disable: true,
      },
    },
  },
  "cls": {
    name: "财联社",
    color: "red",
    column: "finance",
    home: "https://www.cls.cn",
    sub: {
      telegraph: {
        title: "电报",
        interval: Time.Fast,
        type: "realtime",
      },
      depth: {
        title: "深度",
      },
      hot: {
        title: "热门",
        type: "hottest",
      },
    },
  },
  "xueqiu": {
    name: "雪球",
    color: "blue",
    home: "https://xueqiu.com",
    column: "finance",
    sub: {
      hotstock: {
        title: "热门股票",
        interval: Time.Realtime,
        type: "hottest",
      },
    },
  },
  "gelonghui": {
    name: "格隆汇",
    color: "blue",
    title: "事件",
    column: "finance",
    type: "realtime",
    interval: Time.Realtime,
    home: "https://www.gelonghui.com",
  },
  "fastbull": {
    name: "法布财经",
    color: "emerald",
    home: "https://www.fastbull.cn",
    column: "finance",
    sub: {
      express: {
        title: "快讯",
        type: "realtime",
        interval: Time.Realtime,
      },
      news: {
        title: "头条",
        interval: Time.Common,
      },
    },
  },
  "solidot": {
    name: "Solidot",
    color: "teal",
    column: "tech",
    home: "https://solidot.org",
    interval: Time.Slow,
  },
  "hackernews": {
    name: "Hacker News",
    color: "orange",
    column: "tech",
    type: "hottest",
    home: "https://news.ycombinator.com/",
  },
  "producthunt": {
    name: "Product Hunt",
    color: "red",
    column: "tech",
    type: "hottest",
    home: "https://www.producthunt.com/",
  },
  "github": {
    name: "Github",
    color: "gray",
    home: "https://github.com/",
    column: "tech",
    sub: {
      "trending-today": {
        title: "Today",
        type: "hottest",
      },
    },
  },
  "bilibili": {
    name: "哔哩哔哩",
    color: "blue",
    home: "https://www.bilibili.com",
    sub: {
      "hot-search": {
        title: "热搜",
        column: "china",
        type: "hottest",
      },
      "hot-video": {
        title: "热门视频",
        disable: "cf",
        column: "china",
        type: "hottest",
      },
      "ranking": {
        title: "排行榜",
        column: "china",
        disable: "cf",
        type: "hottest",
        interval: Time.Common,
      },
    },
  },
  "kuaishou": {
    name: "快手",
    type: "hottest",
    column: "china",
    color: "orange",
    // cloudflare pages cannot access
    disable: "cf",
    home: "https://www.kuaishou.com",
  },
  "kaopu": {
    name: "靠谱新闻",
    column: "world",
    color: "gray",
    interval: Time.Common,
    desc: "不一定靠谱，多看多思考",
    home: "https://kaopu.news/",
  },
  "jin10": {
    name: "金十数据",
    column: "finance",
    color: "blue",
    type: "realtime",
    home: "https://www.jin10.com",
  },
  "baidu": {
    name: "百度热搜",
    column: "china",
    color: "blue",
    type: "hottest",
    home: "https://www.baidu.com",
  },
  "linuxdo": {
    name: "LINUX DO",
    column: "tech",
    color: "slate",
    home: "https://linux.do/",
    disable: true,
    sub: {
      latest: {
        title: "最新",
        home: "https://linux.do/latest",
      },
      hot: {
        title: "今日最热",
        type: "hottest",
        interval: Time.Common,
        home: "https://linux.do/hot",
      },
    },
  },
  "ghxi": {
    name: "果核剥壳",
    column: "china",
    color: "yellow",
    home: "https://www.ghxi.com/",
    disable: true,
  },
  "smzdm": {
    name: "什么值得买",
    column: "china",
    color: "red",
    type: "hottest",
    home: "https://www.smzdm.com",
    disable: true,
  },
  "nowcoder": {
    name: "牛客",
    column: "china",
    color: "blue",
    type: "hottest",
    home: "https://www.nowcoder.com",
  },
  "sspai": {
    name: "少数派",
    column: "tech",
    color: "red",
    type: "hottest",
    home: "https://sspai.com",
  },
  "juejin": {
    name: "稀土掘金",
    column: "tech",
    color: "blue",
    type: "hottest",
    home: "https://juejin.cn",
  },
  "ifeng": {
    name: "凤凰网",
    column: "china",
    color: "red",
    type: "hottest",
    title: "热点资讯",
    home: "https://www.ifeng.com",
  },
  "chongbuluo": {
    name: "虫部落",
    column: "china",
    color: "green",
    home: "https://www.chongbuluo.com",
    sub: {
      latest: {
        title: "最新",
        interval: Time.Common,
        home: "https://www.chongbuluo.com/forum.php?mod=guide&view=newthread",
      },
      hot: {
        title: "最热",
        type: "hottest",
        interval: Time.Common,
        home: "https://www.chongbuluo.com/forum.php?mod=guide&view=hot",
      },
    },
  },
  "douban": {
    name: "豆瓣",
    column: "china",
    title: "热门电影",
    color: "green",
    type: "hottest",
    home: "https://www.douban.com",
  },
  "steam": {
    name: "Steam",
    column: "world",
    title: "在线人数",
    color: "blue",
    type: "hottest",
    home: "https://store.steampowered.com",
  },
  "tencent": {
    name: "腾讯新闻",
    column: "china",
    color: "blue",
    home: "https://news.qq.com",
    sub: {
      hot: {
        title: "综合早报",
        type: "hottest",
        interval: Time.Common,
        home: "https://news.qq.com/tag/aEWqxLtdgmQ=",
      },
    },
  },
  "freebuf": {
    name: "Freebuf",
    column: "china",
    title: "网络安全",
    color: "green",
    type: "hottest",
    home: "https://www.freebuf.com/",
  },

  "qqvideo": {
    name: "腾讯视频",
    column: "china",
    color: "blue",
    home: "https://v.qq.com/",
    sub: {
      "tv-hotsearch": {
        title: "热搜榜",
        type: "hottest",
        interval: Time.Common,
        home: "https://v.qq.com/channel/tv",

      },
    },
  },
  "iqiyi": {
    name: "爱奇艺",
    column: "china",
    color: "green",
    home: "https://www.iqiyi.com",
    sub: {
      "hot-ranklist": {
        title: "热播榜",
        type: "hottest",
        interval: Time.Common,
        home: "https://www.iqiyi.com",
      },
    },
  },

  // ===== 实时列专属：复用主流官方大平台 / 短视频的抓取器，仅进入「实时」列 =====
  "weiboRealtime": {
    name: "微博",
    title: "实时热搜",
    type: "realtime",
    color: "red",
    interval: Time.Realtime,
    home: "https://weibo.com",
  },
  "baiduRealtime": {
    name: "百度热搜",
    title: "实时热搜",
    type: "realtime",
    color: "blue",
    interval: Time.Realtime,
    home: "https://www.baidu.com",
  },
  "toutiaoRealtime": {
    name: "今日头条",
    title: "实时热搜",
    type: "realtime",
    color: "red",
    interval: Time.Realtime,
    home: "https://www.toutiao.com",
  },
  "thepaperRealtime": {
    name: "澎湃新闻",
    title: "热榜",
    type: "realtime",
    color: "gray",
    interval: Time.Common,
    home: "https://www.thepaper.cn",
  },
  "ifengRealtime": {
    name: "凤凰网",
    title: "热点资讯",
    type: "realtime",
    color: "red",
    interval: Time.Realtime,
    home: "https://www.ifeng.com",
  },
  "tencentRealtime": {
    name: "腾讯新闻",
    title: "综合早报",
    type: "realtime",
    color: "blue",
    interval: Time.Common,
    home: "https://news.qq.com",
  },
  "bilibiliRealtime": {
    name: "哔哩哔哩",
    title: "热搜",
    type: "realtime",
    color: "blue",
    interval: Time.Realtime,
    home: "https://www.bilibili.com",
  },
  "douyinRealtime": {
    name: "抖音",
    title: "实时热搜",
    type: "realtime",
    color: "gray",
    interval: Time.Realtime,
    home: "https://www.douyin.com",
  },
  "kuaishouRealtime": {
    name: "快手",
    title: "实时热搜",
    type: "realtime",
    color: "orange",
    interval: Time.Realtime,
    home: "https://www.kuaishou.com",
  },

  // ===== 国际顶级期刊 / 预印本：每个期刊一个独立看板 =====
  "nature": {
    name: "Nature",
    title: "Nature 最新论文",
    column: "nature",
    color: "emerald",
    interval: Time.Common,
    home: "https://www.nature.com",
    desc: "Nature 期刊最新发表论文",
  },
  "cell": {
    name: "Cell",
    title: "Cell 最新论文",
    column: "cell",
    color: "teal",
    interval: Time.Common,
    home: "https://www.cell.com",
    desc: "Cell 期刊最新发表论文",
  },
  "pnas": {
    name: "PNAS",
    title: "PNAS 最新论文",
    column: "pnas",
    color: "purple",
    interval: Time.Common,
    home: "https://www.pnas.org",
    desc: "Proceedings of the National Academy of Sciences 最新发表论文",
  },
  "nejm": {
    name: "NEJM",
    title: "NEJM 最新论文",
    column: "nejm",
    color: "red",
    interval: Time.Common,
    home: "https://www.nejm.org",
    desc: "New England Journal of Medicine 最新发表论文",
  },
  "arxiv": {
    name: "arXiv",
    title: "arXiv 预印本",
    column: "arxiv",
    color: "blue",
    interval: Time.Common,
    home: "https://arxiv.org",
    desc: "arXiv 预印本平台最新论文（AI/ML 与物理等学科）",
  },

  // ===== 国际顶级期刊 / 预印本（顶刊广场，按学科配色）=====
  "science": {
    name: "Science",
    title: "Science 最新论文",
    column: "science",
    color: "blue",
    interval: Time.Common,
    home: "https://www.science.org",
    desc: "Science 期刊最新发表论文",
  },
  "sciadv": {
    name: "Science Advances",
    title: "Science Advances 最新论文",
    column: "sciadv",
    color: "sky",
    interval: Time.Common,
    home: "https://www.science.org",
    desc: "Science 子刊 Science Advances 最新论文",
  },
  "elife": {
    name: "eLife",
    title: "eLife 最新论文",
    column: "elife",
    color: "fuchsia",
    interval: Time.Common,
    home: "https://elifesciences.org",
    desc: "eLife 期刊最新发表论文",
  },
  "bmj": {
    name: "BMJ",
    title: "BMJ 最新论文",
    column: "bmj",
    color: "rose",
    interval: Time.Common,
    home: "https://www.bmj.com",
    desc: "英国医学期刊 BMJ 最新论文",
  },
  "natcomm": {
    name: "Nature Communications",
    title: "Nature Communications 最新论文",
    column: "natcomm",
    color: "emerald",
    interval: Time.Common,
    home: "https://www.nature.com",
    desc: "Nature 子刊 Nature Communications 最新论文",
  },
  "natmed": {
    name: "Nature Medicine",
    title: "Nature Medicine 最新论文",
    column: "natmed",
    color: "red",
    interval: Time.Common,
    home: "https://www.nature.com",
    desc: "Nature 子刊 Nature Medicine 最新论文",
  },
  "natbiotech": {
    name: "Nature Biotechnology",
    title: "Nature Biotechnology 最新论文",
    column: "natbiotech",
    color: "pink",
    interval: Time.Common,
    home: "https://www.nature.com",
    desc: "Nature 子刊 Nature Biotechnology 最新论文",
  },
  "natgen": {
    name: "Nature Genetics",
    title: "Nature Genetics 最新论文",
    column: "natgen",
    color: "violet",
    interval: Time.Common,
    home: "https://www.nature.com",
    desc: "Nature 子刊 Nature Genetics 最新论文",
  },
  "natphys": {
    name: "Nature Physics",
    title: "Nature Physics 最新论文",
    column: "natphys",
    color: "cyan",
    interval: Time.Common,
    home: "https://www.nature.com",
    desc: "Nature 子刊 Nature Physics 最新论文",
  },
  "natchem": {
    name: "Nature Chemistry",
    title: "Nature Chemistry 最新论文",
    column: "natchem",
    color: "amber",
    interval: Time.Common,
    home: "https://www.nature.com",
    desc: "Nature 子刊 Nature Chemistry 最新论文",
  },
  "natmat": {
    name: "Nature Materials",
    title: "Nature Materials 最新论文",
    column: "natmat",
    color: "lime",
    interval: Time.Common,
    home: "https://www.nature.com",
    desc: "Nature 子刊 Nature Materials 最新论文",
  },
  "natneuro": {
    name: "Nature Neuroscience",
    title: "Nature Neuroscience 最新论文",
    column: "natneuro",
    color: "indigo",
    interval: Time.Common,
    home: "https://www.nature.com",
    desc: "Nature 子刊 Nature Neuroscience 最新论文",
  },
  "natclimate": {
    name: "Nature Climate Change",
    title: "Nature Climate Change 最新论文",
    column: "natclimate",
    color: "teal",
    interval: Time.Common,
    home: "https://www.nature.com",
    desc: "Nature 子刊 Nature Climate Change 最新论文",
  },
  "natmethods": {
    name: "Nature Methods",
    title: "Nature Methods 最新论文",
    column: "natmethods",
    color: "orange",
    interval: Time.Common,
    home: "https://www.nature.com",
    desc: "Nature 子刊 Nature Methods 最新论文",
  },
  "natmicrobiol": {
    name: "Nature Microbiology",
    title: "Nature Microbiology 最新论文",
    column: "natmicrobiol",
    color: "rose",
    interval: Time.Common,
    home: "https://www.nature.com",
    desc: "Nature 子刊 Nature Microbiology 最新论文",
  },
  "natplants": {
    name: "Nature Plants",
    title: "Nature Plants 最新论文",
    column: "natplants",
    color: "green",
    interval: Time.Common,
    home: "https://www.nature.com",
    desc: "Nature 子刊 Nature Plants 最新论文",
  },
  "natrevcancer": {
    name: "Nature Reviews Cancer",
    title: "Nature Reviews Cancer 最新论文",
    column: "natrevcancer",
    color: "red",
    interval: Time.Common,
    home: "https://www.nature.com",
    desc: "Nature Reviews 系列 Nature Reviews Cancer 最新论文",
  },
  "natrevneuro": {
    name: "Nature Reviews Neuroscience",
    title: "Nature Reviews Neuroscience 最新论文",
    column: "natrevneuro",
    color: "violet",
    interval: Time.Common,
    home: "https://www.nature.com",
    desc: "Nature Reviews 系列 Nature Reviews Neuroscience 最新论文",
  },

  // ===== 学术数据库 / 出版平台：经 Crossref 公开 API 实时获取最新论文 =====
  "pubmed": {
    name: "PubMed",
    title: "PubMed 最新论文",
    column: "pubmed",
    color: "emerald",
    interval: Time.Common,
    home: "https://pubmed.ncbi.nlm.nih.gov",
    desc: "PubMed 生物医学文献最新论文（E-utilities 实时抓取）",
  },
  "webofscience": {
    name: "Web of Science",
    title: "Web of Science",
    column: "webofscience",
    color: "blue",
    interval: Time.Common,
    home: "https://www.webofscience.com",
    desc: "跨学科引文索引，经 Crossref 呈现近一年高被引论文",
  },
  "sciencedirect": {
    name: "ScienceDirect",
    title: "ScienceDirect",
    column: "sciencedirect",
    color: "orange",
    interval: Time.Common,
    home: "https://www.sciencedirect.com",
    desc: "Elsevier 出版平台，经 Crossref 实时获取最新论文",
  },
  "springerlink": {
    name: "SpringerLink",
    title: "SpringerLink",
    column: "springerlink",
    color: "green",
    interval: Time.Common,
    home: "https://link.springer.com",
    desc: "Springer 出版平台，经 Crossref 实时获取最新论文",
  },
  "wiley": {
    name: "Wiley Online Library",
    title: "Wiley Online Library",
    column: "wiley",
    color: "red",
    interval: Time.Common,
    home: "https://onlinelibrary.wiley.com",
    desc: "Wiley 出版平台，经 Crossref 实时获取最新论文",
  },
  "ebsco": {
    name: "EBSCO",
    title: "EBSCO（Academic Search Complete）",
    column: "ebsco",
    color: "teal",
    interval: Time.Common,
    home: "https://www.ebsco.com",
    desc: "跨学科聚合库，经 Crossref 呈现全学科最新论文",
  },
  "ieee": {
    name: "IEEE Xplore",
    title: "IEEE Xplore",
    column: "ieee",
    color: "cyan",
    interval: Time.Common,
    home: "https://ieeexplore.ieee.org",
    desc: "IEEE 出版平台，经 Crossref 实时获取最新论文",
  },
  "iopscience": {
    name: "IOPscience",
    title: "IOPscience（英国皇家物理学会）",
    column: "iopscience",
    color: "violet",
    interval: Time.Common,
    home: "https://iopscience.iop.org",
    desc: "英国物理学会出版平台，经 Crossref 实时获取最新论文",
  },
  "asce": {
    name: "ASCE Library",
    title: "ASCE Library",
    column: "asce",
    color: "amber",
    interval: Time.Common,
    home: "https://ascelibrary.org",
    desc: "美国土木工程师学会出版平台，经 Crossref 实时获取最新论文",
  },
  "reaxys": {
    name: "Reaxys",
    title: "Reaxys",
    column: "reaxys",
    color: "fuchsia",
    interval: Time.Common,
    home: "https://www.reaxys.com",
    desc: "化学数据库，经 Crossref 呈现化学领域最新论文",
  },
  "sage": {
    name: "SAGE Journals",
    title: "SAGE Journals",
    column: "sage",
    color: "rose",
    interval: Time.Common,
    home: "https://journals.sagepub.com",
    desc: "SAGE 出版平台，经 Crossref 实时获取最新论文",
  },
  "psycinfo": {
    name: "PsycINFO",
    title: "PsycINFO",
    column: "psycinfo",
    color: "indigo",
    interval: Time.Common,
    home: "https://www.apa.org/pubs/databases/psycinfo",
    desc: "APA 心理学数据库，经 Crossref 实时获取最新论文",
  },
  // ===== 国家职能部门官网最新政策：通用抓取器，新增部门只改 server/utils/policy.ts =====
  "policy_gov": {
    name: "国务院",
    title: "最新政策",
    color: "red",
    interval: Time.Common,
    home: "https://www.gov.cn/zhengce/",
    desc: "中国政府网国务院政策文件库最新发布",
  },
  "policy_ndrc": {
    name: "国家发展改革委",
    title: "最新政策",
    color: "amber",
    interval: Time.Common,
    home: "https://www.ndrc.gov.cn/",
    desc: "国家发展改革委政策发布",
  },
  "policy_mof": {
    name: "财政部",
    title: "最新政策",
    color: "green",
    interval: Time.Common,
    home: "http://www.mof.gov.cn/",
    desc: "财政部政策与财政新闻",
  },
  "policy_moe": {
    name: "教育部",
    title: "最新政策",
    color: "blue",
    interval: Time.Common,
    home: "http://www.moe.gov.cn/",
    desc: "教育部政策文件与通知公告",
  },
  "policy_most": {
    name: "科技部",
    title: "最新政策",
    color: "cyan",
    interval: Time.Common,
    home: "https://www.most.gov.cn/",
    desc: "科技部政策与社会公开信息",
  },
  "policy_pbc": {
    name: "中国人民银行",
    title: "最新政策",
    color: "orange",
    interval: Time.Common,
    home: "http://www.pbc.gov.cn/",
    desc: "中国人民银行政策与公开信息",
  },
  "policy_csrc": {
    name: "证监会",
    title: "最新政策",
    color: "violet",
    interval: Time.Common,
    home: "http://www.csrc.gov.cn/",
    desc: "证监会政策与监管公开信息",
  },
  "policy_chinatax": {
    name: "国家税务总局",
    title: "最新政策",
    color: "teal",
    interval: Time.Common,
    home: "http://www.chinatax.gov.cn/",
    desc: "国家税务总局税收政策与公告",
  },
  "policy_mohrss": {
    name: "人力资源社会保障部",
    title: "最新政策",
    color: "fuchsia",
    interval: Time.Common,
    home: "http://www.mohrss.gov.cn/",
    desc: "人社部政策与通知公告",
  },
  "policy_miit": {
    name: "工业和信息化部",
    title: "最新政策",
    color: "indigo",
    interval: Time.Common,
    home: "https://www.miit.gov.cn/",
    desc: "工信部政策与行业管理信息",
  },
  // ===== 民生相关职能部门（国家统计局 + 医疗 / 民政 / 住房 / 三农 / 市场监管 / 生态 / 交通 等）=====
  "policy_stats": {
    name: "国家统计局",
    title: "最新发布",
    color: "sky",
    interval: Time.Common,
    home: "https://www.stats.gov.cn/sj/zxfb/",
    desc: "国家统计局最新统计数据发布",
  },
  // ===== 国家统计局「数据看板」专用数据栏目 =====
  "stats_sjjd": {
    name: "统计数据解读",
    title: "权威解读",
    color: "cyan",
    interval: Time.Common,
    home: "https://www.stats.gov.cn/sj/sjjd/",
    desc: "国家统计局对最新统计数据与指标的权威解读",
  },
  "stats_tjgb": {
    name: "年度统计公报",
    title: "统计公报",
    color: "amber",
    interval: Time.Slow,
    home: "https://www.stats.gov.cn/sj/tjgb/ndtjgb/",
    desc: "国家统计局年度国民经济和社会发展统计公报",
  },
  "stats_pbc": {
    name: "金融统计数据报告",
    title: "央行月报",
    color: "red",
    interval: Time.Common,
    home: "http://www.pbc.gov.cn/diaochatongjisi/116219/116225/index.html",
    desc: "中国人民银行金融统计数据报告（货币供应、信贷等）",
  },
  "stats_pbc2": {
    name: "金融统计调查",
    title: "央行调查",
    color: "orange",
    interval: Time.Common,
    home: "http://www.pbc.gov.cn/diaochatongjisi/116219/116319/index.html",
    desc: "中国人民银行金融统计调查与统计数据",
  },
  "stats_mof": {
    name: "财政收支情况",
    title: "财政月报",
    color: "emerald",
    interval: Time.Common,
    home: "http://www.mof.gov.cn/zhengwuxinxi/caizhengshuju/",
    desc: "财政部全国财政收支情况月度数据",
  },
  "intl_wb": {
    name: "世界银行指标",
    title: "公开指标",
    color: "lime",
    interval: Time.Slow,
    home: "https://data.worldbank.org/indicator",
    desc: "世界银行公开发展指标目录（WDI）",
  },
  "policy_nhsa": {
    name: "国家医疗保障局",
    title: "最新政策",
    color: "rose",
    interval: Time.Common,
    home: "https://www.nhsa.gov.cn/",
    desc: "国家医保局医保政策与通知公告",
  },
  "policy_mca": {
    name: "民政部",
    title: "最新政策",
    color: "purple",
    interval: Time.Common,
    home: "https://www.mca.gov.cn/n152/n165/index.html",
    desc: "民政部通知公告与政策发布",
  },
  "policy_mohurd": {
    name: "住房和城乡建设部",
    title: "最新政策",
    color: "yellow",
    interval: Time.Common,
    home: "https://www.mohurd.gov.cn/",
    desc: "住建部住房与城乡建设政策与公告",
  },
  "policy_moa": {
    name: "农业农村部",
    title: "最新政策",
    color: "lime",
    interval: Time.Common,
    home: "https://www.moa.gov.cn/",
    desc: "农业农村部三农政策与通知公告",
  },
  "policy_samr": {
    name: "国家市场监督管理总局",
    title: "最新政策",
    color: "slate",
    interval: Time.Common,
    home: "https://www.samr.gov.cn/",
    desc: "市场监管总局市场监督与消费政策",
  },
  "policy_mee": {
    name: "生态环境部",
    title: "最新政策",
    color: "pink",
    interval: Time.Common,
    home: "https://www.mee.gov.cn/",
    desc: "生态环境部生态环境政策与公告",
  },
  "policy_mot": {
    name: "交通运输部",
    title: "最新政策",
    color: "gray",
    interval: Time.Common,
    home: "https://www.mot.gov.cn/",
    desc: "交通运输部交通运输政策与通知",
  },
  // ===== 国务院组成部门（其余）=====
  "policy_mfa": {
    name: "外交部",
    title: "政策文件",
    color: "cyan",
    interval: Time.Common,
    home: "https://www.mfa.gov.cn/web/ziliao_674904/zcwj_674915/",
    desc: "外交部政策文件与条约文件",
  },
  "policy_mod": {
    name: "国防部",
    title: "国防文件",
    color: "red",
    interval: Time.Common,
    home: "http://www.mod.gov.cn/gfbw/fgwx/wj_213958/index.html",
    desc: "国防部发布的文件与法规文献",
  },
  "policy_mnr": {
    name: "自然资源部",
    title: "政策解读",
    color: "lime",
    interval: Time.Common,
    home: "https://www.mnr.gov.cn/gk/zcjd/",
    desc: "自然资源部政策解读与通知公告",
  },
  "policy_mwr": {
    name: "水利部",
    title: "工作动态",
    color: "sky",
    interval: Time.Common,
    home: "http://www.mwr.gov.cn/",
    desc: "水利部工作动态与江河水利管理信息",
  },
  "policy_mofcom": {
    name: "商务部",
    title: "政策发布",
    color: "amber",
    interval: Time.Common,
    home: "https://www.mofcom.gov.cn/zwgk/zcfb/index.html",
    desc: "商务部政策发布与商务新闻",
  },
  "policy_mct": {
    name: "文化和旅游部",
    title: "政策公文",
    color: "pink",
    interval: Time.Common,
    home: "https://www.mct.gov.cn/",
    desc: "文化和旅游部政策公文与通知",
  },
  "policy_mva": {
    name: "退役军人事务部",
    title: "最新动态",
    color: "violet",
    interval: Time.Common,
    home: "https://www.mva.gov.cn/",
    desc: "退役军人事务部最新动态与政策",
  },
  "policy_mem": {
    name: "应急管理部",
    title: "工作动态",
    color: "orange",
    interval: Time.Common,
    home: "https://www.mem.gov.cn/",
    desc: "应急管理与安全生产工作动态",
  },
  "policy_audit": {
    name: "审计署",
    title: "最新动态",
    color: "teal",
    interval: Time.Common,
    home: "https://www.audit.gov.cn/",
    desc: "审计署公告、报告与工作动态",
  },
  // ===== 国务院直属机构 / 直属事业单位 =====
  "policy_nrta": {
    name: "国家广播电视总局",
    title: "总局动态",
    color: "indigo",
    interval: Time.Common,
    home: "https://www.nrta.gov.cn/",
    desc: "国家广播电视总局新闻与政策",
  },
  "policy_sport": {
    name: "国家体育总局",
    title: "体育要闻",
    color: "green",
    interval: Time.Common,
    home: "https://www.sport.gov.cn/",
    desc: "国家体育总局时政要闻与体育工作信息",
  },
  "policy_forestry": {
    name: "国家林业和草原局",
    title: "林草动态",
    color: "emerald",
    interval: Time.Common,
    home: "https://www.forestry.gov.cn/",
    desc: "国家林草局林草生态保护与产业发展动态",
  },
  "policy_cnipa": {
    name: "国家知识产权局",
    title: "最新动态",
    color: "fuchsia",
    interval: Time.Common,
    home: "https://www.cnipa.gov.cn/",
    desc: "知识产权保护运用与专利商标工作动态",
  },
  "policy_natcm": {
    name: "国家中医药管理局",
    title: "最新动态",
    color: "purple",
    interval: Time.Common,
    home: "http://www.natcm.gov.cn/",
    desc: "中医药管理局政策与工作动态",
  },
  "policy_spb": {
    name: "国家邮政局",
    title: "最新动态",
    color: "slate",
    interval: Time.Common,
    home: "https://www.spb.gov.cn/gjyzj/c100009/c100010/common_list.shtml",
    desc: "国家邮政局通知公告与行业政策",
  },
  "policy_cma": {
    name: "中国气象局",
    title: "气象动态",
    color: "gray",
    interval: Time.Common,
    home: "https://www.cma.gov.cn/",
    desc: "中国气象局气象服务与防灾减灾信息",
  },
  "policy_lswz": {
    name: "国家粮食和物资储备局",
    title: "粮食动态",
    color: "yellow",
    interval: Time.Common,
    home: "https://www.lswz.gov.cn/",
    desc: "粮食和物资储备政策与安全监管信息",
  },
  "policy_nea": {
    name: "国家能源局",
    title: "能源动态",
    color: "rose",
    interval: Time.Common,
    home: "https://www.nea.gov.cn/",
    desc: "国家能源局能源政策与保供信息",
  },
  "policy_safe": {
    name: "国家外汇管理局",
    title: "外汇动态",
    color: "blue",
    interval: Time.Common,
    home: "https://www.safe.gov.cn/",
    desc: "外汇管理政策与国际收支数据",
  },
  "policy_cac": {
    name: "中央网信办",
    title: "网信动态",
    color: "indigo",
    interval: Time.Common,
    home: "https://www.cac.gov.cn/",
    desc: "网络信息化与网络安全政策动态",
  },
  "policy_sasac": {
    name: "国务院国资委",
    title: "国资动态",
    color: "orange",
    interval: Time.Common,
    home: "http://www.sasac.gov.cn/",
    desc: "国务院国有资产监督管理信息",
  },
  "policy_sac": {
    name: "国家标准委",
    title: "标准动态",
    color: "teal",
    interval: Time.Common,
    home: "https://www.sac.gov.cn/",
    desc: "国家标准化管理委员会标准制修订动态",
  },
  "policy_nra": {
    name: "国家铁路局",
    title: "铁路动态",
    color: "lime",
    interval: Time.Common,
    home: "https://www.nra.gov.cn/xwzx/",
    desc: "国家铁路局新闻资讯与行业监管",
  },
  // ===== 其他国家机关 =====
  "policy_npc": {
    name: "中国人大网",
    title: "立法动态",
    color: "red",
    interval: Time.Common,
    home: "http://www.npc.gov.cn/",
    desc: "全国人大立法与执法检查动态",
  },
  "policy_cppcc": {
    name: "中国政协网",
    title: "政协动态",
    color: "amber",
    interval: Time.Common,
    home: "http://www.cppcc.gov.cn/zxxw/yw/",
    desc: "全国政协会议与要闻动态",
  },
  "policy_court": {
    name: "最高人民法院",
    title: "司法动态",
    color: "cyan",
    interval: Time.Common,
    home: "https://www.court.gov.cn/",
    desc: "最高人民法院审判与司法改革动态",
  },
  "policy_spp": {
    name: "最高人民检察院",
    title: "检察动态",
    color: "violet",
    interval: Time.Common,
    home: "https://www.spp.gov.cn/spp/tzgg1/index.shtml",
    desc: "最高人民检察院通知公告与检察动态",
  },
  "policy_gwytb": {
    name: "国务院台办",
    title: "对台政策",
    color: "sky",
    interval: Time.Common,
    home: "http://www.gwytb.gov.cn/",
    desc: "国务院台湾事务办公室政策与对台信息",
  },
  "policy_hmo": {
    name: "国务院港澳办",
    title: "港澳政策",
    color: "pink",
    interval: Time.Common,
    home: "http://www.hmo.gov.cn/",
    desc: "国务院港澳事务办公室政策与港澳信息",
  },
  "policy_cast": {
    name: "中国科协",
    title: "科协动态",
    color: "emerald",
    interval: Time.Common,
    home: "https://www.cast.org.cn/",
    desc: "中国科学技术协会科普与科技工作者工作",
  },
  "policy_cdpf": {
    name: "中国残联",
    title: "残联动态",
    color: "fuchsia",
    interval: Time.Common,
    home: "https://www.cdpf.org.cn/",
    desc: "中国残疾人联合会残疾人事业信息",
  },
  "jama": {
    name: "JAMA",
    title: "最新期刊",
    color: "red",
    interval: Time.Slow,
    home: "https://jamanetwork.com/journals/jama",
    desc: "美国医学会杂志 JAMA：临床医学与卫生政策顶级期刊",
  },
  "lancet": {
    name: "The Lancet",
    title: "最新论文",
    color: "rose",
    interval: Time.Slow,
    home: "https://www.thelancet.com",
    desc: "柳叶刀：全球最具影响力医学期刊之一",
  },
  "neuron": {
    name: "Neuron",
    title: "最新论文",
    color: "indigo",
    interval: Time.Slow,
    home: "https://www.cell.com/neuron/home",
    desc: "细胞 Press：神经科学顶级期刊",
  },
  "immunity": {
    name: "Immunity",
    title: "最新论文",
    color: "sky",
    interval: Time.Slow,
    home: "https://www.cell.com/immunity/home",
    desc: "细胞 Press：免疫学顶级期刊",
  },
  "cancercell": {
    name: "Cancer Cell",
    title: "最新论文",
    color: "fuchsia",
    interval: Time.Slow,
    home: "https://www.cell.com/cancer-cell/home",
    desc: "细胞 Press：肿瘤学顶级期刊",
  },
  "cellreports": {
    name: "Cell Reports",
    title: "最新论文",
    color: "violet",
    interval: Time.Slow,
    home: "https://www.cell.com/cell-reports/home",
    desc: "细胞 Press：Cell 主刊研究论文",
  },
  "natrevgen": {
    name: "Nature Reviews Genetics",
    title: "综述",
    color: "emerald",
    interval: Time.Slow,
    home: "https://www.nature.com/nrg/",
    desc: "Nature Reviews：遗传学权威综述",
  },
  "natrevdrug": {
    name: "Nature Reviews Drug Discovery",
    title: "综述",
    color: "teal",
    interval: Time.Slow,
    home: "https://www.nature.com/nrd/",
    desc: "Nature Reviews：药物发现权威综述",
  },
  "biorxiv": {
    name: "bioRxiv",
    title: "预印本",
    color: "lime",
    interval: Time.Slow,
    home: "https://www.biorxiv.org/",
    desc: "生物学预印本平台最新论文",
  },
  "medrxiv": {
    name: "medRxiv",
    title: "预印本",
    color: "green",
    interval: Time.Slow,
    home: "https://www.medrxiv.org/",
    desc: "医学预印本平台最新论文",
  },
  "preprints": {
    name: "Preprints.org",
    title: "预印本",
    color: "amber",
    interval: Time.Slow,
    home: "https://www.preprints.org/",
    desc: "多学科预印本平台最新论文",
  },
  "plosone": {
    name: "PLOS ONE",
    title: "最新论文",
    color: "orange",
    interval: Time.Slow,
    home: "https://journals.plos.org/plosone",
    desc: "PLOS ONE：开放获取综合性期刊",
  },
  "plosbio": {
    name: "PLOS Biology",
    title: "最新论文",
    color: "yellow",
    interval: Time.Slow,
    home: "https://journals.plos.org/plosbiology",
    desc: "PLOS Biology：开放获取生命科学期刊",
  },
  "jmlr": {
    name: "JMLR",
    title: "最新论文",
    color: "purple",
    interval: Time.Slow,
    home: "https://www.jmlr.org/",
    desc: "Journal of Machine Learning Research：机器学习顶刊",
  },
} as const satisfies Record<string, OriginSource>

export function genSources() {
  const _: [SourceID, Source][] = []

  Object.entries(originSources).forEach(([id, source]: [any, OriginSource]) => {
    const parent = {
      name: source.name,
      type: source.type,
      disable: source.disable,
      desc: source.desc,
      column: source.column,
      home: source.home,
      color: source.color ?? "primary",
      interval: source.interval ?? Time.Default,
    }
    if (source.sub && Object.keys(source.sub).length) {
      Object.entries(source.sub).forEach(([subId, subSource], i) => {
        if (i === 0) {
          _.push([
            id,
            {
              redirect: `${id}-${subId}`,
              ...parent,
              ...subSource,
            },
          ] as [any, Source])
        }
        _.push([`${id}-${subId}`, { ...parent, ...subSource }] as [
          any,
          Source,
        ])
      })
    } else {
      _.push([
        id,
        {
          title: source.title,
          ...parent,
        },
      ])
    }
  })

  return typeSafeObjectFromEntries(
    _.filter(([_, v]) => {
      if (v.disable === "cf" && process.env.CF_PAGES) {
        return false
      } else {
        return v.disable !== true
      }
    }),
  )
}
