/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShortvideoRouteImport } from './routes/shortvideo'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as JournalsRouteImport } from './routes/journals'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HotboardIndexRouteImport } from './routes/hotboard/index'
import { Route as HotboardPlatformRouteImport } from './routes/hotboard/$platform'
import { Route as CColumnRouteImport } from './routes/c.$column'

const ShortvideoRoute = ShortvideoRouteImport.update({
  id: '/shortvideo',
  path: '/shortvideo',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalsRoute = JournalsRouteImport.update({
  id: '/journals',
  path: '/journals',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HotboardIndexRoute = HotboardIndexRouteImport.update({
  id: '/hotboard/',
  path: '/hotboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const HotboardPlatformRoute = HotboardPlatformRouteImport.update({
  id: '/hotboard/$platform',
  path: '/hotboard/$platform',
  getParentRoute: () => rootRouteImport,
} as any)
const CColumnRoute = CColumnRouteImport.update({
  id: '/c/$column',
  path: '/c/$column',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/journals': typeof JournalsRoute
  '/policies': typeof PoliciesRoute
  '/shortvideo': typeof ShortvideoRoute
  '/c/$column': typeof CColumnRoute
  '/hotboard/$platform': typeof HotboardPlatformRoute
  '/hotboard/': typeof HotboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/journals': typeof JournalsRoute
  '/policies': typeof PoliciesRoute
  '/shortvideo': typeof ShortvideoRoute
  '/c/$column': typeof CColumnRoute
  '/hotboard/$platform': typeof HotboardPlatformRoute
  '/hotboard': typeof HotboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/journals': typeof JournalsRoute
  '/policies': typeof PoliciesRoute
  '/shortvideo': typeof ShortvideoRoute
  '/c/$column': typeof CColumnRoute
  '/hotboard/$platform': typeof HotboardPlatformRoute
  '/hotboard/': typeof HotboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/journals'
    | '/policies'
    | '/shortvideo'
    | '/c/$column'
    | '/hotboard/$platform'
    | '/hotboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/journals'
    | '/policies'
    | '/shortvideo'
    | '/c/$column'
    | '/hotboard/$platform'
    | '/hotboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/journals'
    | '/policies'
    | '/shortvideo'
    | '/c/$column'
    | '/hotboard/$platform'
    | '/hotboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  JournalsRoute: typeof JournalsRoute
  PoliciesRoute: typeof PoliciesRoute
  ShortvideoRoute: typeof ShortvideoRoute
  CColumnRoute: typeof CColumnRoute
  HotboardPlatformRoute: typeof HotboardPlatformRoute
  HotboardIndexRoute: typeof HotboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shortvideo': {
      id: '/shortvideo'
      path: '/shortvideo'
      fullPath: '/shortvideo'
      preLoaderRoute: typeof ShortvideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journals': {
      id: '/journals'
      path: '/journals'
      fullPath: '/journals'
      preLoaderRoute: typeof JournalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotboard/': {
      id: '/hotboard/'
      path: '/hotboard'
      fullPath: '/hotboard/'
      preLoaderRoute: typeof HotboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotboard/$platform': {
      id: '/hotboard/$platform'
      path: '/hotboard/$platform'
      fullPath: '/hotboard/$platform'
      preLoaderRoute: typeof HotboardPlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$column': {
      id: '/c/$column'
      path: '/c/$column'
      fullPath: '/c/$column'
      preLoaderRoute: typeof CColumnRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  JournalsRoute: JournalsRoute,
  PoliciesRoute: PoliciesRoute,
  ShortvideoRoute: ShortvideoRoute,
  CColumnRoute: CColumnRoute,
  HotboardPlatformRoute: HotboardPlatformRoute,
  HotboardIndexRoute: HotboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
